
--CREATE DATABASE
CREATE DATABASE [SHOPPING]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SHOPPING', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SHOPPING.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SHOPPING_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\SHOPPING_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [SHOPPING] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SHOPPING].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

--CREATE SHEMA 
CREATE SCHEMA SOL

--CREATE TABLE
CREATE TABLE [SOL].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Descripcion] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


--INSERT DATOS


INSERT INTO SOL.Product(Nombre,Descripcion)
		VALUES('PRODUCTO A','PRODUCTO A DESCRIPCION'),
			('PRODUCTO B','PRODUCTO B DESCRIPCION')